openapi: 3.2.0
info:
  title: Settings Methods Put And Patch Not Allowed. API
  version: unknown
servers:
- url: https://sandbox.elationemr.com/api/2.0
security:
- sec0: []
tags:
- name: Methods Put And Patch Not Allowed.
paths:
  /Methods Put and Patch not allowed.:
    patch:
      summary: '[WIP] Methods Put and Patch not allowed.Update Message Thread'
      description: ''
      operationId: update-message-threadwip-methods-put-and-patch-not-allowed
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      tags:
      - Methods Put And Patch Not Allowed.
components:
  securitySchemes:
    sec0:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://example.com/oauth2/token
          scopes: {}
x-readme:
  headers: []
x-readme-fauxas: true
